name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/crates-io-auth-action@v1
        id: cratesio-auth
      - name: Publish crates
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.cratesio-auth.outputs.token }}
